'use strict';

/* eslint-disable */

const requests = [
  ['refunded', 'refunded'],
  ['refund', 'refund'],
  ['reversed', 'reversed'],
  ['reverse', 'reverse'],
  ['returned', 'returned'],
  ['return', 'return'],
  ['reimbursed', 'reimbursed'],
  ['reimburse', 'reimburse'],
  ['credited', 'credited'],
  ['credit', 'credit'],
  ['reimbursement', 'reimbursement'],
  ['return my money', 'return my money'],
  ['cancel the charge', 'cancel the charge'],
  ['cancel charge', 'cancel charge'],
  ['cancel the transaction', 'cancel the transaction'],
  ['cancel transaction', 'cancel transaction'],
  ['cancel the payment', 'cancel the payment'],
  ['cancel payment', 'cancel payment'],
  ['cancel the fees', 'cancel the fees'],
  ['cancel fee', 'cancel fee'],
  ['cancel the order', 'cancel the order'],
  ['cancel order', 'cancel order'],
  ['cancel the debit', 'cancel the debit'],
  ['cancel debit', 'cancel debit'],
  ['give my money back', 'give my money back'],
  ['money back', 'money back'],
  ['moneyback', 'moneyback'],
  ['want my money back', 'want my money back'],
  ['want to receive my money back', 'want to receive my money back'],
  ['reverse the charge', 'reverse the charge'],
  ['reverse charge', 'reverse charge'],
  ['remove charge', 'remove charge'],
  ['get rid of the charge', 'get rid of the charge'],
  ['get rid of charge', 'get rid of charge'],
  ['redeem the charge', 'redeem the charge'],
  ['redeem charge', 'redeem charge'],
  ['redeem', 'redeem'],
  ['send my money back', 'send my money back'],
  ['credit me', 'credit me'],
  ['credit the charge', 'credit the charge'],
  ['credit charge', 'credit charge'],
  ['credit card', 'credit card'],
  ['credit the card', 'credit the card'],
  ['will I get a refund', 'refund'],
  ['I want my returns', 'want my returns'],
  ['remit', 'remit'],
  ['withdraw the charge', 'withdraw the charge'],
  ['withdraw charge', 'withdraw charge'],
  ['withdraw', 'withdraw'],
  ['I should be fully refunded', 'refunded'],
  ['adjust the payment', 'adjust the payment'],
  ['adjust payment', 'adjust payment'],
  ['adjust', 'adjust'],
  ['adjust the charge', 'adjust the charge'],
  ['adjust charge', 'adjust charge'],
  ['adjust the transaction', 'adjust the transaction'],
  ['adjust transaction', 'adjust transaction'],
  ['adjust the fee', 'adjust the fee'],
  ['adjust fee', 'adjust fee'],
  ['adjust the order', 'adjust the order'],
  ['adjust order', 'adjust order'],
  ['block these charges', 'block these charges'],
  ['block charges', 'block charges'],
  ['retract this charge', 'retract this charge'],
  ['retract', 'retract'],
  ['repay', 'repay'],
  ['cancel purchase', 'cancel purchase'],
  ['you pretended to be', 'pretended'],
  ['pretended', 'pretended'],
  ['disguising yourself', 'disguising'],
  ['disguising', 'disguising'],
  ['subscription is misleading', 'misleading'],
  ['misleading', 'misleading'],
  ['I was conned', 'conned'],
  ['conned', 'conned'],
  ['con', 'con'],
  ['you deceived me', 'deceived'],
  ['deceived', 'deceived'],
  ['deceiving', 'deceiving'],
  ['you have fooled me', 'fooled me'],
  ['fooled me', 'fooled me'],
  ['fooled', 'fooled'],
  ['I got tricked by you', 'got tricked'],
  ['I got tricked', 'got tricked'],
  ['got tricked', 'got tricked'],
  ['I was tricked into your sub', 'was tricked'],
  ['led to believe you are', 'led to believe'],
  ['I\'ve been duped', 'duped'],
  ['been duped', 'duped'],
  ['duped', 'duped'],
  ['I was misguided', 'misguided'],
  ['misguided', ''],
  ['I was bamboozled', 'bamboozled'],
  ['bamboozled', 'bamboozled'],
  ['bamboozle', 'bamboozled'],
  ['I feel taken advantage of', 'taken advantage'],
  ['taken advantage', 'taken advantage'],
  ['the price was not disclosed truthfully', 'not disclosed'],
  ['was not disclosed', 'not disclosed'],
  ['you shafted me', 'shafted'],
  ['shafted', 'shafted'],
  ['deceptive practice', 'deceptive practice'],
  ['deceptive', 'deceptive'],
  ['this was hidden trap', 'hidden trap'],
  ['hidden trap', 'hidden trap'],
  ['you didn\'t tell me at the time that there would be a monthly fee', 'didn\'t tell'],
  ['bait', 'bait'],
  ['deception', 'deception'],
  ['repay what you have cheated', 'repay'],
  ['cheated', 'cheated'],
  ['false advertising', 'false advertising'],
  ['owe me', 'owe me'],
  ['hoax', 'hoax'],
  ['rip off', 'rip off'],
  ['ripoff', 'ripoff'],
  ['I was rooked', 'rooked'],
  ['rooked', 'rooked'],
  ['robbers', 'robbers'],
  ['robbery', 'robbery'],
  ['robber', 'robber'],
  ['rob', 'rob'],
  ['cheat', 'cheat'],
  ['cheaters', 'cheater'],
  ['cheater', 'cheaters'],
  ['thieves', 'thieves'],
  ['thieve', 'thieve'],
  ['charlatan', 'charlatan'],
  ['charlatans', 'charlatans'],
  ['deceivers', 'deceivers'],
  ['deceiver', 'deceiver'],
  ['crooks', 'crooks'],
  ['crook', 'crook'],
  ['impostor', 'impostor'],
  ['impostors', 'impostors'],
  ['bogus', 'bogus'],
  ['rascals', 'rascals'],
  ['rascal', 'rascal'],
  ['scam', 'scam'],
  ['scammer', 'scammer'],
  ['scammers', 'scammers'],
  ['con artists', 'con artists'],
  ['illegal', 'illegal'],
  ['stole my money', 'stole my money'],
  ['the amounts were taken illegally from my account', 'illegally'],
  ['illegally', 'illegally'],
  ['crime', 'crime'],
  ['abuse', 'abuse'],
  ['elder abuse', 'elser abuse'],
];

module.exports = requests;
